# !!! Generate a token by the command: 
#     php bin/console app:jwt

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NzMyMjQxMTQsImV4cCI6MTc3MzIyNzcxNCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiZGVidWdAbG9jYWwifQ.ItI9tHvz9-W_Mzcq_he1or9eRVA_H4EpuZBBWdMKEhDOb163uESydnHWTyeYJ9zH3uhaVYJKCJ60a-ayqr5ZkuunKLVUbqT_SJUT4okt72MQdVtEpY6IMTDnHyOzerL85cR5x25Uz0nQdLmIvukFfm7tBNtVHhMf1-pNxUtYDFVi28tgF6ow5QA-0LpESqF5KCiyIHDqGUUlhkr4aoEtrTHB1Wak6AdTVnKyGd9YVy9ZjYOY3_5Yr__HJnemXBfWUTbatMZbJNCg5qy7Mku7FyrtZC21zdWVP1hkR_sUwzd3REhQaKea3qQoSHNFwvNxePZggt78QynTs29K8o0RVw
@url = http://localhost:8080
# @url = http://localhost:8000

#------------------ Company -----------------

### Create company
POST {{url}}/api/companies
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "NewComp1",
  "email": "newcomp1@example.com"
}

### Create company Error
POST {{url}}/api/companies
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "",
  "email": "wrong-email"
}

### Get company by Id
GET {{url}}/api/companies/7
Content-Type: application/json

### Get companies
GET {{url}}/api/companies
Content-Type: application/json

### Update company
PUT {{url}}/api/companies/19
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Newcomp2",
  "email": "newcomp2example.com"
}

### Delete company
DELETE {{url}}/api/companies/21
Authorization: Bearer {{token}}
Content-Type: application/json

#------------------ Employee -----------------

### Create employee
POST {{url}}/api/employees
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Employee1",
  "email": "employee1@example.com",
  "companyId": 7
}

### Get employee by Id
GET {{url}}/api/employees/17
Content-Type: application/json

### Get employees
GET {{url}}/api/employees
Content-Type: application/json

### Update employee
PUT {{url}}/api/employees/17
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Employee2",
  "email": "employee2@example.com",
  "companyId": 2
}

### Delete employee
DELETE {{url}}/api/employees/38
Authorization: Bearer {{token}}
Content-Type: application/json

#------------------ Project -----------------

### Create project
POST {{url}}/api/projects
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Project2",
  "description": "Description for Project2",
  "companyId": 2
}

### Get projects
GET {{url}}/api/projects
Content-Type: application/json

### Get project by Id
GET {{url}}/api/projects/1
Content-Type: application/json

### Update project
PUT {{url}}/api/projects/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Project1",
  "description": "New Date: Description for Project1",
  "companyId": 1
}

### Delete project
DELETE {{url}}/api/projects/2
Authorization: Bearer {{token}}
Content-Type: application/json
