# !!! Generate a token by the command: 
#     php bin/console app:jwt

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NzMwNTkyMTIsImV4cCI6MTc3MzA2MjgxMiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiZGVidWdAbG9jYWwifQ.r1bzexMlskbI8zW3idaBgnlNMgvDDoelrsmELhb0I9KqenSkrIgLQxcHVPveltVFrRJ9SkQf1wz5jbSL2XTsgwc1_pVD31ir6DfNGcq1rpn7vpLy8LyvSRhOd2ggVgrjs9OI_75pKct_tmDlljLh-wy9nEHifl3qW-dwsttWag-AJZdZtvtFA6aR78p1UiNb7pB1Q4imcWrWn5XHk-2VT7Ies9tEJTMMz3h6AxzA8zw-ZlIBlVF0g_nksEmT6ckGjvHAiq3k-kmKqtpk_Wtkex2ETFn8aEQqQlea7ss55ONDIuCb9eQ1xPjX5XaSCuXGuRaPnZIBvyZM_xK_Da2tXQ

@url = http://localhost:8080
# @url = http://localhost:8000

#------------------ Company -----------------

### Create company
POST {{url}}/api/companies
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "NewComp1",
  "email": "newcomp1@example.com"
}

### Create company Error
POST {{url}}/api/companies
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "",
  "email": "wrong-email"
}

### Get company by Id
GET {{url}}/api/companies/7
Content-Type: application/json

### Get companies
GET {{url}}/api/companies
Content-Type: application/json

### Update company
PUT {{url}}/api/companies/19
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Newcomp2",
  "email": "newcomp2example.com"
}

### Delete company
DELETE {{url}}/api/companies/21
Authorization: Bearer {{token}}
Content-Type: application/json

#------------------ Employee -----------------

### Create employee
POST {{url}}/api/employees
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Employee1",
  "email": "employee1@example.com",
  "companyId": 1
}

### Get employee by Id
GET {{url}}/api/employees/14
Content-Type: application/json

### Get employees
GET {{url}}/api/employees
Content-Type: application/json

### Update employee
PUT {{url}}/api/employees/16
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Employee2",
  "email": "employee2@example.com",
  "companyId": 2
}

### Delete employee
DELETE {{url}}/api/employees/16
Authorization: Bearer {{token}}
Content-Type: application/json

#------------------ Project -----------------

### Create project
POST {{url}}/api/projects
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Project2",
  "description": "Description for Project2",
  "companyId": 2
}

### Get projects
GET {{url}}/api/projects
Content-Type: application/json

### Get project by Id
GET {{url}}/api/projects/1
Content-Type: application/json

### Update project
PUT {{url}}/api/projects/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Project1",
  "description": "New Date: escription for Project1",
  "companyId": 1
}

### Delete project
DELETE {{url}}/api/projects/2
Authorization: Bearer {{token}}
Content-Type: application/json
